export const INCREMENT = 'increment'
export const DECREMENT = 'decrement'
export const INCREMENTCOUNT = 'incrementCount'
export const ADDSTU = 'addStu'
export const UPDATEINFO = 'updateinfo'
export const AUPDATEINFO = 'aUpdateInfo'